Update target-image-sync.yml

diff --git a/.github/workflows/target-image-sync.yml b/.github/workflows/target-image-sync.yml
--- a/.github/workflows/target-image-sync.yml
+++ b/.github/workflows/target-image-sync.yml
@@ -14,6 +14,10 @@ jobs:
     if: contains(github.event.issue.labels.*.name, 'sync image')
     env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # REGISTRY: ${{ secrets.REGISTRY }}
+      # NAME_SPACE: ${{ secrets.NAME_SPACE }}
+      # USER: ${{ secrets.USER }}
+      # PASSWORD: ${{ secrets.PASSWORD }}
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
@@ -44,22 +48,35 @@ jobs:
       run: |
         ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
         gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步中...<br>[详情请查看](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
-    - name: Set up crproxy
-      run: |
-        wget https://github.com/DaoCloud/crproxy/releases/download/v0.7.0-rc.42/crproxy_linux_amd64 -O /usr/local/bin/crproxy && chmod +x /usr/local/bin/crproxy
-        /usr/local/bin/crproxy -a :8000 ${{ secrets.CRPROXY_ARGS }} &
-    - name: Sync Images
+  
+    - name: Login to Docker Hub
+      uses: docker/login-action@v1
+      with:
+        registry: ${{ secrets.REGISTRY }}
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+    - name: Sync Docker Image
       run: |
         ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
-        curl --fail -X PUT "http://127.0.0.1:8000/internal/api/image/sync?image=${ORIGIN_IMAGE}"
-        # if ! ./hack/verify-allows.sh ./allows.txt "${ORIGIN_IMAGE}"; then
-        #   gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步完成<br>请使用 m.daocloud.io/${ORIGIN_IMAGE} 替代源镜像<br>这个镜像不在白名单列表里, 在未来可能将无法访问<br>将其添加到[白名单](https://github.com/DaoCloud/public-image-mirror/blob/main/allows.txt)"
-        # else
-        #   gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步完成<br>请使用 m.daocloud.io/${ORIGIN_IMAGE} 替代源镜像"
-        # fi
+        TARGET_IMAGE="${{ secrets.REGISTRY }}/${ORIGIN_IMAGE}"
+        docker pull ${ORIGIN_IMAGE}
+        docker tag ${ORIGIN_IMAGE} ${TARGET_IMAGE}
+        docker push ${TARGET_IMAGE}
         gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步完成<br>请使用 m.daocloud.io/${ORIGIN_IMAGE} 替代源镜像"
         gh issue edit ${{ github.event.issue.number }} --add-label "sync image succeeded" -b "IMAGE SYNC"
         gh issue close ${{ github.event.issue.number }} --reason "completed"
+    # - name: Sync Images
+    #   run: |
+    #     ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
+    #     # curl --fail -X PUT "http://127.0.0.1:8000/internal/api/image/sync?image=${ORIGIN_IMAGE}"
+    #     # if ! ./hack/verify-allows.sh ./allows.txt "${ORIGIN_IMAGE}"; then
+    #     #   gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步完成<br>请使用 m.daocloud.io/${ORIGIN_IMAGE} 替代源镜像<br>这个镜像不在白名单列表里, 在未来可能将无法访问<br>将其添加到[白名单](https://github.com/DaoCloud/public-image-mirror/blob/main/allows.txt)"
+    #     # else
+    #     #   gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步完成<br>请使用 m.daocloud.io/${ORIGIN_IMAGE} 替代源镜像"
+    #     # fi
+    #     gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步完成<br>请使用 m.daocloud.io/${ORIGIN_IMAGE} 替代源镜像"
+    #     gh issue edit ${{ github.event.issue.number }} --add-label "sync image succeeded" -b "IMAGE SYNC"
+    #     gh issue close ${{ github.event.issue.number }} --reason "completed"
     - name: Fail Sync
       if: failure()
       run: |
